#ifndef WEBCOREFUNCTIONS_GLOBAL_H
#define WEBCOREFUNCTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBCOREFUNCTIONS_LIBRARY)
#  define WEBCOREFUNCTIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBCOREFUNCTIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBCOREFUNCTIONS_GLOBAL_H
